export enum MetricEnum {
  AverageSuccessPayments = 'averageSuccessPayments',
  ConversionRate = 'conversionRate',
  CountNewPayments = 'countNewPayments',
  CountPaidPayments = 'countPaidPayments',
  CountRefunds = 'countRefunds',
  CountSessions = 'countSessions',
  CountSuccessPayments = 'countSuccessPayments',
  CountUnsuccessfulPayments = 'countUnsuccessfulPayments',
  ExitRate = 'exitRate',
  MaxSuccessPayments = 'maxSuccessPayments',
  MinSuccessPayments = 'minSuccessPayments',
  RateNewPayments = 'rateNewPayments',
  RatePaidPayments = 'ratePaidPayments',
  RateRefundPayments = 'rateRefundPayments',
  RateSuccessPayments = 'rateSuccessPayments',
  Revenue = 'revenue',
  SessionDuration = 'sessionDuration',
  TotalCount = 'totalCount',
}
